print("Ohh Ohh Ohh Ohh Oh Oh Ohh Ohh")
print("Sweet Little Bumble Bee")
print("I know what You want from Me")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Sweet Little Bumble Bee")
print("More than just a Fantasy")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("My Heart skips a Beat when You walk in the Room")
print("I go Boom Boom Boom You go Zoom Zoom Zoom")
print("You're My Playboy Playtoy Lover, My Friend")
print("I wanna be with You until the End")
print("I give My Heart and Soul to You to make You see it's True")
print("I'm so Confused Baby can't You see? Please come and Rescue Me!")
print("Sweet Little Bumble Bee")
print("I know what You want from Me")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Sweet Little Bumble Bee")
print("More than just a Fantasy")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Ohh Ohh Ohh Ohh Oh Oh Ohh Ohh")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Ohh Ohh Ohh Ohh Oh Oh Ohh Ohh")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("I start to Cry when You walk out the Door")
print("You go Bye Bye Bye I go why why why")
print("I'm so Lonely and only waiting for You to come back and tell Me i Love You")
print("I give My Heart and Soul to You to make You see it's True")
print("I'm so Confused Baby can't You see? Please come and Rescue Me!")
print("Sweet Little Bumble Bee")
print("I know what You want from Me")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Sweet Little Bumble Bee")
print("More than just a Fantasy")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Ohh Ohh Ohh Ohh Oh Oh Ohh Ohh")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Ohh Ohh Ohh Ohh Oh Oh Ohh Ohh")
print("Dubi Dubi Du Dah Dah") 
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Sweet Little Bumble Bee")
print("I know what You want from Me")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Sweet Little Bumble Bee")
print("More than just a Fantasy")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Ohh Ohh Ohh Ohh Oh Oh Ohh Ohh")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")
print("Ohh Ohh Ohh Ohh Oh Oh Ohh Ohh")
print("Dubi Dubi Du Dah Dah")
print("Dubi Dubi Du Dah Dah")