from turtle import Turtle,Screen
a=Turtle()
a.shape("turtle")
a.speed(10)
a.color("red","green")
a.begin_fill()
a.circle(100)
a.end_fill()
a.rt(90)
a.penup() # pu(), up()
a.fd(100)
a.pendown() # pd(), down()
a.hideturtle()
a.pensize(5)
a.color("green","orange")
a.begin_fill()
a.circle(50)
a.end_fill()
print(a.pos())
a.goto(-100,-100) # setposition(x,y) or setpos(x,y)
a.showturtle()
a.screen.mainloop()