from turtle import Turtle,Screen
gullu=Turtle()
gulluScreen=Screen()
gulluScreen.bgcolor("black")
gullu.color("red","green")
gullu.shape("turtle")
gullu.speed(0)
for i in range(150):
    # gullu.pu()
    gullu.fd(i)
    # gullu.pd()
    gullu.circle(i)
    gullu.lt(90)
    gullu.circle(i)
    # gullu.pu()
    gullu.fd(i)
    # gullu.pd()
    gullu.circle(i)
    gullu.lt(90)
    gullu.circle(i)
    # gullu.pu()
    gullu.fd(i)
    # gullu.pd()
    gullu.circle(i)
    gullu.lt(90)
    gullu.circle(i)
    # gullu.pu()
    gullu.fd(i)
    # gullu.pd()
    gullu.circle(i)
    i+=1
gullu.screen.mainloop()