student_data=[
    {
        'name':'Vaibhav',
        'roll_no':48,
        'age':19,
        'course':'Python'
    },
    {
        'name':'Sanjana',
        'roll_no':41,
        'age':18,
        'course':'C++'},
    {
        'name':'Sahil',
        'roll_no':40,
        'age':20,
        'course':'JavaScript'
    }
]
def newStudentEntry(name,roll_no,age,course):
    new_student={}
    new_student['name']=name
    new_student['roll_no']=roll_no
    new_student['age']=age
    new_student['course']=course
    student_data.append(new_student)
newStudentEntry("Shraddha",43,20,"C")
print(student_data)