import keyword
help(keyword)

"""
O/p: Help on module keyword:
     
     NAME
         keyword - Keywords (from "Grammar/python.gram")
     
     MODULE REFERENCE
         https://docs.python.org/3.13/library/keyword.html
     
         The following documentation is automatically generated from the Python
         source files.  It may be incomplete, incorrect or include features that
         are considered implementation detail and may vary between Python
         implementations.  When in doubt, consult the module reference at the
         location listed above.
     
     DESCRIPTION
         This file is automatically generated; please don't muck it up!
     
         To update the symbols in this file, 'cd' to the top directory of
         the python source tree and run:
     
             PYTHONPATH=Tools/peg_generator python3 -m pegen.keywordgen         Grammar/python.gram         Grammar/Tokens         Lib/keyword.py
     
         Alternatively, you can run 'make regen-keyword'.
     
     FUNCTIONS
         iskeyword = __contains__(object, /) method of builtins.frozenset instance
             x.__contains__(y) <==> y in x.
     
         issoftkeyword = __contains__(object, /) method of builtins.frozenset instance
             x.__contains__(y) <==> y in x.
     
     DATA
         __all__ = ['iskeyword', 'issoftkeyword', 'kwlist', 'softkwlist']
         kwlist = ['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'aw...
         softkwlist = ['_', 'case', 'match', 'type']
     
     FILE
         d:\programming\python\python\interpreter\lib\keyword.py
     
     
"""