from turtle import Turtle,Screen
a=Turtle()
a.shape("turtle")
a.speed(10)
a.color("red","green")
a.begin_fill()
a.circle(100)
a.end_fill()
a.rt(90)
a.penup() # pu(), up()
a.fd(100)
a.pendown() # pd(), down()
a.circle(50)
a.screen.mainloop()