data=[
    {
        'name':'Vaibhav',
        'subscribers':2100,
        'description':'Gamer',
        'city':'Indore'
    },
    {
        'name':'Ayush',
        'subscribers':2000,
        'description':'Gamer',
        'city':'Indore'
    },
    {
        'name':'Anjali',
        'subscribers':1500,
        'description':'Vlogger',
        'city':'Dewas'
    },
    {
        'name':'Shraddha',
        'subscribers':2500,
        'description':'Dancer',
        'city':'Amla'
    },
    {
        'name':'Adonis',
        'subscribers':1800,
        'description':'Boxer',
        'city':'Sagar'
    },
    {
        'name':'Mayank',
        'subscribers':1400,
        'description':'Botanist',
        'city':'Ujjain'
    }
]